lms_frontend/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.api import RegisterServiceplan
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include

urlpatterns = [
    path('', include('user_management.urls')),
    path('', include('mainapp.urls')),
    path('', include('valuechain_milestone.urls')),
    path('register-serviceplan/', RegisterServiceplan.as_view(), name='register-serviceplan' ),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import *
from .EDMS_views import *

urlpatterns = [
    
    path("company_selecting/",company_selecting, name="company_selecting"),
    path("dashboard/",dashboard, name="dashboard"),

    path('company/', company_create, name='company'),
    path('company-view/', company_view, name='company_view'),
    path('company-edit/<pk>/', company_edit, name='company_edit'),
    path('company-delete/<pk>/', company_delete, name='company_delete'),
    path('company-list/', customer_list, name='customer_list'),
  
    path('customer/', customer_create, name='customer'),
    path('customer-view', customer_view, name='customer_view'),
    path('customer-edit/<pk>/', customer_edit, name='customer_edit'),
    path('customer-delete/<pk>/', customer_delete, name='customer_delete'),

    path('customer_list/', customer_list, name='customerlist'),
    path('uploadmultidocument_customer/<pk>/', uploadmultidocument_customer, name='uploadmultidocumentcustomer'),

    # path('customerdocuments/', customerdocuments_create, name='customerdocuments'),
    path('customer_view_fordoc/', customer_view_fordoc, name='customer_view_fordoc'),

    path('loanapplication/', loanapplication_create, name='loanapplication'),
    path('loanapplication-view/', loanapplication_view, name='loanapplication_view'),
    path('loanapplication_summary/<pk>/', loanapplication_summary, name='loanapplication_summary'),
    path('loanapplication-edit/<pk>/', loanapplication_edit, name='loanapplication_edit'),
    path('loanapplication-delete/<pk>/', loanapplication_delete, name='loanapplication_delete'),
    path('view_loan_applications/', view_loan_applications, name='view_loanapplications'),
    path('application_status_tracking/<pk>/', application_status_tracking, name='applicationstatus_tracking'),

    path('document_varification/', document_varification, name='document_varification'),
    path('verify_documents/<pk>/', verify_documents, name='verify_documents'),

    path('show_active_applications/', show_active_applications, name='show_active_applications'),
    path('eligibility_status/<pk>/', eligibility_status, name='eligibility_status'),

    path('loan_risk_assessment/', loan_risk_assessment_list, name='assessmentlist'),
    path('loan_risk_assessment/<pk>/', loan_risk_assessment_detail, name='loan_risk_assessment_detail'),

    path('loan_approval_view/', loan_approval_view, name='loanapprovalview'),
    path('loan_approval/<pk>/', loan_approval, name='loanapproval'),

    path('list_approved_applications/', list_approved_applications, name='listapprovedapplications'),
    path('create_agreement/<pk>/', create_agreement, name='createagreement'),
    path('agreement_review/<loanapp_id>/<template_id>/', agreement_review, name='agreement_review'),
    path('list_agreement/', list_agreement, name='list_agreement'),
    path('agreement_confirmation/<pk>', agreement_confirmation, name='agreementconfirmation'),
    path('edit_agreement/<pk>', edit_agreement, name='editagreement'),

    path('disbursement_request/', disbursement_request, name='disbursementrequest'),
    path('disply_agreed_agreement/<pk>', disply_agreed_agreement, name='displyagreedagreement'),
    path('disply_loans/', disply_loans, name='disply_loans'),
    path('disbursement/<loanid>/', disbursement_create, name='disbursement'),
    path('disbursement_details/', disbursement_details, name='disbursement_details'),
    path('show_disbursement_details/<pk>/', show_disbursement_details, name='show_disbursement_details'),

    path('show_loandetails/',show_loandetails,name='show_loandetails'),
    path('create_collateral/<pk>/', create_collateral, name='create_collateral'),
    path('create_collateraldocument/<pk>/', create_collateraldocument, name='create_collateraldocument'),
    path('collaterals-view/', collaterals_view, name='collaterals_view'),
    path('collateral_details/<pk>/', collateral_details, name='collateral_details'),
    path('collaterals-edit/<pk>/', collaterals_edit, name='collaterals_edit'),
    path('collaterals-delete/<pk>/', collaterals_delete, name='collaterals_delete'),
    
    path('disbursed_loans/', disbursed_loans, name='disbursed_loans'),
    path('repayment_schedule/<pk>/', repayment_schedule, name='repayment_schedule'),
    path('disbursedloans_foroverview/', disbursedloans_foroverview, name='disbursedloans_foroverview'),
    path('schedule_overview/<pk>/', schedule_overview, name='schedule_overview'),
    path('loancalculators/', loancalculators_create, name='loancalculators'),

    path('loan_list/', loan_list, name='loan_list'),
    path('account_list/<id>', account_list, name='account_list'),
    
#--------------- repayment 2 ----------------------
    path('disbursed_loans1/', disbursed_loans1, name='disbursed_loans1'),
    path('repayment_schedule1/<pk>/', repayment_schedule1, name='repayment_schedule1'),
    path('disbursedloans_foroverview1/', disbursedloans_foroverview1, name='disbursedloans_foroverview1'),
    path('schedule_overview1/<pk>/', schedule_overview1, name='schedule_overview1'),
    path('payment_process/<schedule_id>/', payment_process, name='payment_process'),

    #=============== Penalties =====================
    path('disply_penaltyloans/', disply_penaltyloans, name='disply_penaltyloans'),
    path('disply_penaltyschedules/<pk>/', disply_penaltyschedules, name='displypenaltyschedules'),
    path('create_penalty/', create_penalty, name='create_penalty'),
    path('penalty_details/', penalty_details, name='penalty_details'),
    path('loanwise_penalty_details/<pk>/', loanwise_penalty_details, name='loanwisepenaltydetails'),

    #================== Setting urls ================
    path('identificationtype/', identificationtype_create, name='identificationtype'),
    path('identificationtype-view/', identificationtype_view, name='identificationtype_view'),
    path('identificationtype-edit/<pk>/', identificationtype_edit, name='identificationtype_edit'),
    path('identificationtype-delete/<pk>/', identificationtype_delete, name='identificationtype_delete'),

    path('bankaccount/', bankaccount_create, name='bankaccount'),
    path('bankaccount-view/', bankaccount_view, name='bankaccount_view'),
    path('bankaccount-edit/<pk>/', bankaccount_edit, name='bankaccount_edit'),
    path('bankaccount-delete/<pk>/', bankaccount_delete, name='bankaccount_delete'),

    path('currency/', currency_create, name='currency'),
    path('currency-view/', currency_view, name='currency_view'),
    path('currency-edit/<pk>/', currency_edit, name='currency_edit'),
    path('currency-delete/<pk>/', currency_delete, name='currency_delete'),

    path('paymentmethod/', paymentmethod_create, name='paymentmethod'),
    path('paymentmethod-view/', paymentmethod_view, name='paymentmethod_view'),
    path('paymentmethod-edit/<pk>/', paymentmethod_edit, name='paymentmethod_edit'),
    path('paymentmethod-delete/<pk>/', paymentmethod_delete, name='paymentmethod_delete'),

    path('collateraltype/', collateraltype_create, name='collateraltype'),
    path('collateraltype-view/', collateraltype_view, name='collateraltype_view'),
    path('collateraltype-edit/<pk>/', collateraltype_edit, name='collateraltype_edit'),
    path('collateraltype-delete/<pk>/', collateraltype_delete, name='collateraltype_delete'),

    path('loantype/', loantype_create, name='loantype'),
    path('loantype-view/', loantype_view, name='loantype_view'),
    path('loantype-edit/<pk>/', loantype_edit, name='loantype_edit'),
    path('loantype-delete/<pk>/', loantype_delete, name='loantype_delete'),


    #==================DMS=====================
    path('matter_workspace/', customer_workspace,name='matter_workspace'),
    path('document_storage/<entity_id>/', document_storage, name='document_storage'),
    path('folder/<entity_id>/<folder_id>/', folder, name='folder'),
    path('client_folder_delete/<entity_id>/<folder_id>/',client_folder_delete,name="client_folder_delete"),

    path('create_folder/<entity_id>/', create_folder,name='create_folder'),
    path('create_sub_folder/<entity_id>/<folder_id>/', create_sub_folder,name='create_sub_folder'),

    path('upload_document/<entity_id>/<folder_id>/', upload_document,name='upload_document'),
    path('document_category/', document_category,name='document_category'),
    path('department/', department,name='department'),
    path('document_type/', document_type,name='document_type'),
    path('document_entity/', document_entity,name='document_entity'),

    path('document_view/<entity_id>/<folder_id>/<document_id>/', document_view,name='document_view'),
    path('document_version/<document_id>/', document_version,name='document_version'),
    #============Ac
    path('customer_folder_delete/<entity_id>/<folder_id>/',customer_folder_delete,name="customer_folder_delete"),
    path('document_delete/<entity_id>/<folder_id>/<document_id>/', document_delete,name='document_delete'),
    path('aggrement_template_create/', aggrement_template_create,name='aggrement_template_create'),
    path('aggrement_template_list/', aggrement_template_list,name='aggrement_template_list'),
    path('aggrement_template_view/<template_id>/', aggrement_template_view,name='aggrement_template_view'),
    path('document_edit/<entity_id>/<folder_id>/', document_edit,name='document_edit'),


    path('audit_view', audit_view, name='audit_view'),
    path('document_list/', document_list, name='document_list'),
    path('customer_document_view/<pk>/',customer_document_view, name='customer_document_view'),
    path('loan_detail_trenches/<loanapp_id>/',loan_detail_trenches, name='loan_detail_trenches'),
    path('loan_upadate_trenches/<loanapp_id>/',loan_upadate_trenches, name='loan_upadate_trenches'),
    path('milestone_edit_v1/<loanapp_id>/',milestone_edit_v1, name='milestone_edit_v1'),
    path('milestone_activity_edit_v1/<loanapp_id>/',milestone_activity_edit_v1, name='milestone_activity_edit_v1'),

user_management/urls.py
from django.urls import path,include
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("",login, name="login"),
    path('logout/', logout, name='logout'),
    # path("dashboard/",dashboard, name="dashboard"),
    path('user_registration/', user_registration, name='user_registration'),
    path('user_list/', user_list, name='user_list'),
    path('user_edit/<pk>/', user_edit, name='user_edit'),
    path('user_view/<pk>/', user_view, name='user_view'),
    path('user_delete/<pk>/', user_delete, name='user_delete'),
    path('roles/', roles, name='roles'),
    path('roles_create/', roles_create, name='roles_create'),
    path('roles_edit/<pk>/', roles_edit, name='roles_edit'),
    path('roles_delete/<pk>/', roles_delete, name='roles_delete'),
    path('permission/<pk>/', permission, name='permission'),
    path('function_setup/', function_setup, name='function_setup'),
    path('multi_factor_authentication/', multi_factor_authentication, name='multi_factor_authentication'),

    path('userprofile_list/', userprofile_list, name='userprofile_list'),
    path('userprofile_create/', userprofile_create, name='userprofile_create'),
    path('userprofile_edit/<id>/', userprofile_edit, name='userprofile_edit'),
    path('userprofile_delete/<id>/', userprofile_delete, name='userprofile_delete'),
    
    path('change_password/', change_password, name='change_password'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('set_password/<email>', set_password, name='set_password'),

    

    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

user_management/forms.py
from django import forms
from .models import *
from django.forms import DateInput, DateTimeInput, TimeInput, CheckboxInput, Textarea, TextInput


class UserRegistrationForm(forms.Form):
    first_name = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(attrs={"class": "form-control"})
    )
    phone_number = forms.CharField(
        max_length=15, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    password = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    user_profile = forms.CharField(
        max_length=100, 
        required=False, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    

    # You can also add validation or custom methods if needed

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if User.objects.filter(email=email).exists():
    #         raise forms.ValidationError("A user with that email already exists.")
    #     return email
    

class LoginForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField()

class RoleForm(forms.Form):
    name = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    description = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )

class UserProfileForm(forms.Form):
    name = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    role =  forms.MultipleChoiceField(
        choices=[],
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        required=True
    )
    description = forms.CharField(
        max_length=100, 
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    def __init__(self, *args, **kwargs):
        role = kwargs.pop('role', [])
        super().__init__(*args, **kwargs)
        if isinstance(role, list):
            self.fields['role'].choices = [
                (str(record.get('id', '')), record.get('name', ''))
                for record in role
            ]

templates/UserManagement/UserProfile.html
{% extends 'base.html' %}

{% block body_block %}


<body>
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>{{ screen_name }}</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Settings</li>
          <li class="breadcrumb-item active">{{ screen_name }}</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Form Layout</h5>

              <!-- Vertical Form -->
              <form method="post" class="row g-3" enctype="multipart/form-data" id="myForm">
                {% csrf_token %}
                

                {% for form_field in form %}
                <div class="col-12">
                  {{ form_field.label_tag }}
                  {{ form_field }}
                  <span class="text-danger">{{ form_field.errors }}</span>
                </div>
                {% endfor %}
                
                {% if not view %}
  <div class="">
    <button type="submit" class="btn btn-primary mr-3">Save</button>
    <a href="javascript:window.history.back()" class="btn btn-secondary">Cancel</a>
  </div>
{% endif %}


              </form><!-- Vertical Form -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->
</body>

{% if view %}
<script>
  // Select the form by ID
  var form = document.getElementById('myForm');
  
  // Loop through all form elements
  for (var i = 0; i < form.elements.length; i++) {
      form.elements[i].disabled = true;
  }
</script>

{% endif %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
      
      $('#id_role').select2({
        placeholder: "--- Select Roles ---", 
        allowClear: true,                   
        width: '100%'                       
      });
    });
  </script>
{% endblock %}

templates/UserManagement/maker_checker_mapping.html
{% extends 'base.html' %}
{% block body_block %}
{% load static %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="content-wrapper">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-header">
                <h3>Maker Checker Mapping</h3>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form.maker.label_tag }}
                                {{ form.maker }}
                                {{ form.maker.errors }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form.checker.label_tag }}
                                {{ form.checker }}
                                {{ form.checker.errors }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/UserManagement/maker_checker_mapping_list.html
{% extends 'base.html' %}
{% block body_block %}
{% load static %}
<div class="content-wrapper">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <a href="{% url 'maker_checker_mapping' %}">
                    <button type="button" class="btn btn-primary float-right">+ New</button>
                </a>
                <h3 class="card-title">Maker Checker List</h3>
                <br><br>
                <div class="table-responsive">
                    <table id="tableID" class="display table table-hover">
                        <thead class="bg-col">
                            <tr>
                                <th>No.</th>
                                <th>Maker</th>
                                <th>Checker </th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in records %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{data.maker}}</td>
                                <td>{{data.checker}}</td>
                                <td>{{data.created_at}}</td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn  dropdown-toggle" type="button" id="dropdownMenuIconButton2"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </button>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuIconButton2">

                                            <a class="dropdown-item">
                                                <button class="btn iconbg-yellow" data-bs-toggle="tooltip"
                                                    data-bs-placement="top" title="Edit"><i
                                                        class="fas fa-eye"></i>View</button>
                                            </a>
                                            <a class="dropdown-item">
                                                <button class="btn iconbg-yellow" data-bs-toggle="tooltip"
                                                    data-bs-placement="top" title="Edit"><i
                                                        class="fas fa-edit"></i>Edit</button>
                                            </a>
                                            <a class="dropdown-item">
                                                <button class="btn iconbg-rose" data-bs-toggle="tooltip"
                                                    data-bs-placement="top" title="Delete"><i
                                                        class="fas fa-trash-alt"></i>Delete</button>
                                            </a>
                                        </div>
                                    </div>
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <br><br><br>

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/UserManagement/otp_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP Verification</title>
    <style>
      body {
        font-family: "Comic Sans MS", cursive;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        background: #fafafa; /* Light grey background */
        color: #333;
      }

      .container {
        width: 100%;
        max-width: 400px;
      }

      .card {
        width: 100%;
        background-color: #f8f8f8; /* Card background color */
        padding: 20px;
        border-radius: 12px; /* Card border radius */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }

      h2 {
        text-align: center;
        color: #333;
      }

      form {
        display: flex;
        flex-direction: column;
      }

      input {
        padding: 10px;
        margin-bottom: 12px;
        border: 2px solid #ddd; /* Input border color */
        border-radius: 8px; /* Input border radius */
        transition: border-color 0.3s ease-in-out;
        outline: none;
        color: #333;
        background-color: #f4f4f4; /* Input background color */
      }

      input:focus {
        border-color: #012970; /* Focused input border color */
      }

      button {
        background-color: #012970; /* Button color */
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 8px; /* Button border radius */
        cursor: pointer;
        transition: background-color 0.3s ease-in-out;
      }

      button:hover {
        background-color: #012970; /* Button hover color */
      }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
          <h2>OTP Verification</h2>
          <form method="post">
            {% csrf_token %}

            <input type="text" id="otp" name="otp" placeholder="Enter OTP" required maxlength="4" pattern="\d{4}">
            <label for="">{{otp_error}}</label>
            {% if email %}
            <input type="hidden"  name="email" value = {{email}}>
            {% endif %}
            <button type="submit">Verify OTP</button>
          </form>
        </div>
      </div>
</body>
</html>

templates/UserManagement/password_change_form.html
{% extends 'base.html' %}

{% block body_block %}
<body>
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Change Password</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item">Settings</li>
          <li class="breadcrumb-item active">Change Password</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-6 offset-lg-3"><!-- Centered Form -->

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Change Password</h5>

              <!-- Change Password Form -->
              <form method="post" class="row g-3" id="changePasswordForm">
                {% csrf_token %}
                
                <div class="col-12">
                  <label for="old_password" class="form-label">Old Password</label>
                  <input type="password" id="old_password" name="old_password" class="form-control" required>
                </div>

                <div class="col-12">
                  <label for="new_password" class="form-label">New Password</label>
                  <input type="password" id="new_password" name="new_password" class="form-control" required>
                </div>

                <div class="col-12">
                  <label for="confirm_password" class="form-label">Confirm New Password</label>
                  <input type="password" id="confirm_password" name="confirm_password" class="form-control" required>
                </div>

                {% if error %}
                <div class="col-12">
                  <span class="text-danger">{{ error }}</span>
                </div>
                {% endif %}

                <div class="col-12 d-flex justify-content-between">
                  <button type="submit" class="btn btn-primary">Change Password</button>
                  <a href="javascript:window.history.back()" class="btn btn-secondary">Cancel</a>
                </div>
              </form><!-- End Change Password Form -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->
</body>
{% endblock %}

templates/UserManagement/permission.html
{% extends 'base.html' %}
{% block body_block %}
{% load static %}

<body>
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>{{ screen_name }}</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Settings</li>
          <li class="breadcrumb-item active">{{ screen_name }}</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12" >

          <div class="card">
            <div class="card-body">
              
              <div class="d-flex justify-content-between align-items-center mb-4 p-2">
                {% if not view %}
                <button type="submit" form="myForm" class="btn btn-success">Save</button>
                {% endif %}
                <div>
                  <a href="javascript:window.history.back()" class="btn btn-danger">Cancel</a>
                  <a href="{% url 'function_setup' %}" class="btn btn-info">Refresh Permissions</a>
                </div>
              </div>

              <div class="card-body">
                <form method="post" enctype="multipart/form-data" id="myForm">
                  {% csrf_token %}
                  <div class="form-check mb-3">
                    <input type="checkbox" class="form-check-input" id="selectAll">
                    <label class="form-check-label" for="selectAll">Select All</label>
                  </div>
                  <hr>
                  <div class="row">
                    {% for data in records %}
                    <div class="col-md-3">
                      <div class="form-check">
                        <input type="checkbox" name="permission" class="form-check-input" id="{{ data.function_id }}" value="{{ data.id }}" {% if data.id in permission_id_list %}checked{% endif %}>
                        <label class="form-check-label" for="{{ data.function_id }}">{{ data.function_name }}</label>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </form>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

</body>

<script>
  document.getElementById('selectAll').addEventListener('change', function() {
    let checkboxes = document.querySelectorAll('.form-check-input');
    checkboxes.forEach(checkbox => {
      checkbox.checked = this.checked;
    });
  });
</script>

{% endblock %}